## Library

In [1]:
# Library Praproses Teks
import pandas as pd
import string
import nltk
import re
import sys
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import numpy as np
from collections import Counter
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer

#Library untuk Analisis Sentimen NBC
import codecs
from sklearn.model_selection import KFold
from sklearn.utils import shuffle
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn import model_selection
from imblearn.over_sampling import SMOTE

## Praproses Teks

In [2]:
# Import data
data = pd.read_excel('D:/VALIDASI/Data TA/Belviu Hotel2.xlsx')

In [3]:
x = data['Review'] #get comment
y = data['Sentimen'] #get class

In [4]:
y.value_counts()

1    686
0     12
Name: Sentimen, dtype: int64

In [5]:
lower = []
for line in x:
    a = line.lower()
    lower.append(a)

In [6]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()
stemmed = map(lambda x: stemmer.stem(x), lower)
translator = str.maketrans('', '', string.punctuation)
no_punc = map(lambda x: x.lower().translate(translator),stemmed)

In [7]:
stopword = open("E:/stopwords/stopwords indonesia.txt","r").read()
final = []
for line in no_punc:
    word_token = nltk.word_tokenize(line)
    word_token = [word for word in word_token if not word in stopword and not word[0].isdigit()]
    final.append(" ".join(word_token))

In [8]:
df_xtrain = pd.DataFrame(final)
df_xtrain.columns=['Review']
df_ytrain = pd.DataFrame(y)
df_xytrain = pd.concat([df_xtrain,df_ytrain],axis=1)
df_xytrain.to_csv('D:/VALIDASI/Praproses/belviu.csv', header=True, index=False, sep=',')

## Frekuensi kemunculan kata tertinggi dari seluruh dokumen

In [2]:
# Import data
datanew = pd.read_excel('D:/VALIDASI/Praproses/belviu.xlsx')
x = datanew['Review'] #get comment
y = datanew['Sentimen'] #get class

In [3]:
a = datanew['Review'].to_list()
tokens = [[text for text in a.split()] for a in a]

In [4]:
token = []
for sublist in tokens:
    for item in sublist:
        token.append(item)

In [5]:
# count word frequency, sort and return just 20
from collections import Counter
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
counter = Counter()
counter.update(token)
most_common = counter.most_common(15)
most_common

[('bagus', 875),
 ('nyaman', 440),
 ('makan', 377),
 ('bersih', 371),
 ('renang', 348),
 ('kolam', 345),
 ('layan', 309),
 ('pandang', 245),
 ('ramah', 235),
 ('lokasi', 198),
 ('strategis', 193),
 ('mode', 167),
 ('sarap', 163),
 ('fasilitas', 156),
 ('rekomendasi', 143)]

## Struktur Data Setelah Praproses Teks

In [6]:
count_vectorizer = CountVectorizer()
countvec = count_vectorizer.fit_transform(token).toarray()
countvec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [7]:
countvec2 = pd.DataFrame(countvec)
countvec2

0     1     2     3     4     5     6     7     8     9     ...  1878  \
0         0     0     0     0     0     0     0     0     0     0  ...     0   
1         0     0     0     0     0     0     0     0     0     0  ...     0   
2         0     0     0     0     0     0     0     0     0     0  ...     0   
3         0     0     0     0     0     0     0     0     0     0  ...     0   
4         0     0     0     0     0     0     0     0     0     0  ...     0   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
11142     0     0     0     0     0     0     0     0     0     0  ...     0   
11143     0     0     0     0     0     0     0     0     0     0  ...     0   
11144     0     0     0     0     0     0     0     0     0     0  ...     0   
11145     0     0     0     0     0     0     0     0     0     0  ...     0   
11146     0     0     0     0     0     0     0     0     0     0  ...     0   

       1879  1880  1881  1882  1883  1884  1885  1886  1887  
0         0     0     0     0     0     0     0     0     0  
1         0     0     0     0     0     0     0     0     0  
2         0     0     0     0     0     0     0     0     0  
3         0     0     0     0     0     0     0     0     0  
4         0     0     0     0     0     0     0     0     0  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
11142     0     0     0     0     0     0     0     0     0  
11143     0     0     0     0     0     0     0     0     0  
11144     0     0     0     0     0     0     0     0     0  
11145     0     0     0     0     0     0     0     0     0  
11146     0     0     0     0     0     0     0     0     0  

[11147 rows x 1888 columns]

In [8]:
c = count_vectorizer.get_feature_names()
c

['abai',
 'abdul',
 'abies',
 'abiiiiss',
 'abis',
 'abisss',
 'abissss',
 'accousticnya',
 'acsesss',
 'activity',
 'adaain',
 'ade',
 'adem',
 'adik',
 'admin',
 'advisor',
 'africa',
 'againt',
 'agent',
 'aghh',
 'agng',
 'agoda',
 'air',
 'airhangat',
 'airmakanan',
 'airny',
 'ajainteriornya',
 'akrab',
 'akses',
 'aktif',
 'aktivitas',
 'aktuf',
 'alacarte',
 'alat',
 'alat2',
 'alet',
 'alhamdulilah',
 'alhdulilah',
 'alias',
 'alir',
 'also',
 'alternatif',
 'always',
 'amenities',
 'amri',
 'anak2',
 'anak2staf',
 'anakny',
 'anaksenang',
 'andai',
 'aneh',
 'aneka',
 'anggun',
 'anniversary',
 'aoalagi',
 'apalg',
 'apalgi',
 'apapundan',
 'apek',
 'appreciate',
 'apslagi',
 'apung',
 'architecture',
 'area',
 'arisan',
 'aroma',
 'arsitektur',
 'arsobers',
 'arstiktik',
 'artistic',
 'artistik',
 'asli',
 'asmila',
 'aspek',
 'asyik',
 'atea',
 'atm',
 'atmosfir',
 'atur',
 'automatis',
 'awesome',
 'ayam',
 'ayo',
 'baagus',
 'baby',
 'badaaii',
 'bagu',
 'bagus',
 'bagusa

In [10]:
countvec3 = pd.DataFrame(countvec, columns=c)
countvec3.head(10)

abai  abdul  abies  abiiiiss  abis  abisss  abissss  accousticnya  acsesss  \
0     0      0      0         0     0       0        0             0        0   
1     0      0      0         0     0       0        0             0        0   
2     0      0      0         0     0       0        0             0        0   
3     0      0      0         0     0       0        0             0        0   
4     0      0      0         0     0       0        0             0        0   
5     0      0      0         0     0       0        0             0        0   
6     0      0      0         0     0       0        0             0        0   
7     0      0      0         0     0       0        0             0        0   
8     0      0      0         0     0       0        0             0        0   
9     0      0      0         0     0       0        0             0        0   

   activity  ...  xtrans  yaang  yahh  yahhhh  yahud  year  your  yuhuuuuu  \
0         0  ...       0      0     0       0      0     0     0         0   
1         0  ...       0      0     0       0      0     0     0         0   
2         0  ...       0      0     0       0      0     0     0         0   
3         0  ...       0      0     0       0      0     0     0         0   
4         0  ...       0      0     0       0      0     0     0         0   
5         0  ...       0      0     0       0      0     0     0         0   
6         0  ...       0      0     0       0      0     0     0         0   
7         0  ...       0      0     0       0      0     0     0         0   
8         0  ...       0      0     0       0      0     0     0         0   
9         0  ...       0      0     0       0      0     0     0         0   

   yummy  yusuf  
0      0      0  
1      0      0  
2      0      0  
3      0      0  
4      0      0  
5      0      0  
6      0      0  
7      0      0  
8      0      0  
9      0      0  

[10 rows x 1888 columns]

In [18]:
#from xlsxwriter.utility import xl_rowcol_to_cell
#saveresult = pd.ExcelWriter('D:/update/train_countvec_belviu.xlsx', engine='xlsxwriter')
#countvec3.to_excel(saveresult, index=False, sheet_name='report')
#saveresult.save()

## Struktur Data Analisis Sentimen

In [11]:
transformer =TfidfTransformer(norm=None, use_idf=True, smooth_idf=False, sublinear_tf=False)
tfidf = transformer.fit_transform(countvec)
tfidf

<11147x1888 sparse matrix of type '<class 'numpy.float64'>'
	with 11147 stored elements in Compressed Sparse Row format>

In [12]:
tfidf1 = tfidf.toarray()
tfidf1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
tfidf2 = pd.DataFrame(tfidf1)
df1 = pd.DataFrame(tfidf1, columns=c)
df1

abai  abdul  abies  abiiiiss  abis  abisss  abissss  accousticnya  \
0       0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
1       0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
2       0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
3       0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
4       0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
...     ...    ...    ...       ...   ...     ...      ...           ...   
11142   0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
11143   0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
11144   0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
11145   0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   
11146   0.0    0.0    0.0       0.0   0.0     0.0      0.0           0.0   

       acsesss  activity  ...  xtrans  yaang  yahh  yahhhh  yahud  year  your  \
0          0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
1          0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
2          0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
3          0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
4          0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
...        ...       ...  ...     ...    ...   ...     ...    ...   ...   ...   
11142      0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
11143      0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
11144      0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
11145      0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   
11146      0.0       0.0  ...     0.0    0.0   0.0     0.0    0.0   0.0   0.0   

       yuhuuuuu  yummy  yusuf  
0           0.0    0.0    0.0  
1           0.0    0.0    0.0  
2           0.0    0.0    0.0  
3           0.0    0.0    0.0  
4           0.0    0.0    0.0  
...         ...    ...    ...  
11142       0.0    0.0    0.0  
11143       0.0    0.0    0.0  
11144       0.0    0.0    0.0  
11145       0.0    0.0    0.0  
11146       0.0    0.0    0.0  

[11147 rows x 1888 columns]

In [22]:
#from xlsxwriter.utility import xl_rowcol_to_cell
#saveresult = pd.ExcelWriter('D:/update/belviu_all_tfidf.xlsx', engine='xlsxwriter')
#df1.to_excel(saveresult, index=False, sheet_name = 'report')
#saveresult.save()

## TF-IDF

In [3]:
#TF-IDF
count_vectorizer=CountVectorizer(binary=True)
countvec_x=count_vectorizer.fit_transform(x)
tfidf_x=TfidfTransformer(use_idf=True).fit_transform(countvec_x)

## Naive Bayes Classifier (tanpa SMOTE)

In [4]:
accuracy1=[]
accuracy2=[]
AUC1=[]
AUC2=[]
nb = BernoulliNB()
kf=KFold(n_splits=10, shuffle=False)
i=1
for train_index, test_index in kf.split(tfidf_x,y):
    print("Fold ",i)
    print("TRAIN :",train_index,"TEST :",test_index)
    x_train ,x_test=tfidf_x[train_index] ,tfidf_x[test_index]
    y_train, y_test=y[train_index], y[test_index]
    i+=1
    
    classify_train=nb.fit(x_train,y_train)
    #prob_train=classify_train.predict_proba(x_train[:10])
    ypred_trainn=classify_train.predict(x_train)
    
    #prob_test=classify_train.predict_proba(x_test[:10])
    ypred_test=classify_train.predict(x_test)
    
    #Evaluasi
    score1=accuracy_score(y_train,ypred_trainn)
    score2=accuracy_score(y_test,ypred_test)
    accuracy1.append(score1)
    accuracy2.append(score2)
    AUC_score1=roc_auc_score(y_train,ypred_trainn)
    AUC1.append(AUC_score1)
    AUC_score2=roc_auc_score(y_test,ypred_test)
    AUC2.append(AUC_score2)
   # print("Probabilitas Klasifikasi NBC Data Training")
   # print(prob_train)
   # print("Probabilitas Klasifikasi NBC Data Testing")
   # print(prob_test)
    print("CONF MATRIX TRAINING TANPA SMOTE")
    print(confusion_matrix(y_train,ypred_trainn))
    print("CONF MATRIX TESTING TANPA SMOTE")
    print(confusion_matrix(y_test, ypred_test))
    print("=================================================================================")

print("AKURASI TRAINING TANPA SMOTE")
print(accuracy1)
print("AKURASI TESTING TANPA SMOTE")
print(accuracy2)
print("AUC TRAINING TANPA SMOTE")
print(AUC1)
print("AUC TESTING TANPA SMOTE")
print(AUC2)

Fold  1
TRAIN : [ 70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105
 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123
 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141
 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159
 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195
 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213
 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231
 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249
 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267
 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285
 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303
 304 305 306 307 308 309 310 311 31

## Rata-rata akurasi dan AUC 10-Fold CV

In [5]:
# SEBELUM SMOTE
print("Sebelum SMOTE:")
jumlah=0
for i in accuracy1:
    jumlah += i
    mean = jumlah / len(accuracy1)
print("Mean accuracy training: ", mean)

jumlah1=0
for j in accuracy2:
    jumlah1 += j
    mean1 = jumlah1 / len(accuracy2)
print("Mean accuracy testing: ", mean1)

jumlah2=0
for k in AUC1:
    jumlah2 += k
    mean2 = jumlah2 / len(AUC1)
print("Mean AUC training: ", mean2)

jumlah3=0
for l in AUC2:
    jumlah3 += l
    mean3 = jumlah3 / len(AUC2)
print("Mean AUC testing: ", mean3)

print("CONF MATRIX TRAINING TANPA SMOTE")
print(confusion_matrix(y_train,ypred_trainn))
print("CONF MATRIX TESTING TANPA SMOTE")
print(confusion_matrix(y_test, ypred_test))

Sebelum SMOTE:
Mean accuracy training:  0.9842404787702652
Mean accuracy testing:  0.9827950310559007
Mean AUC training:  0.5418181818181818
Mean AUC testing:  0.5
CONF MATRIX TRAINING TANPA SMOTE
[[  1   9]
 [  0 619]]
CONF MATRIX TESTING TANPA SMOTE
[[ 0  2]
 [ 0 67]]


## Naive Bayes Classifier (dengan SMOTE)

In [6]:
#Training model WITH SMOTE (tf-idf sudah dilakukan diawal sebelum k-fold)
sm_train = SMOTE(k_neighbors=1, random_state=42)
tfidf_train2, y_train2 = sm_train.fit_sample(x_train,y_train)
classify_train2=nb.fit(tfidf_train2,y_train2)
ypred_train2=classify_train2.predict(x_train)
prob_train2=classify_train.predict_proba(x_train)
prediction3 = pd.DataFrame(ypred_train2,columns=['predictions']).to_csv("D:/VALIDASI/Prediksi NBC/Belviu TRAIN SMOTE_.csv")
tfidf_test2, y_test2 = sm_train.fit_sample(x_test,y_test)
classify_test2=nb.fit(tfidf_test2, y_test2)
ypred_test2=classify_test2.predict(x_test)
prob_test2=classify_train.predict_proba(x_test)
prediction4 = pd.DataFrame(ypred_test2,columns=['predictions']).to_csv("D:/VALIDASI/Prediksi NBC/Belviu TEST SMOTE_.csv")

In [8]:
print("HASIL NAIVE BAYES SMOTED")
print(" ")
print("AKURASI TRAINING SMOTED: ", accuracy_score(y_train,ypred_train2))
print("AKURASI TESTING SMOTED: ", accuracy_score(y_test, ypred_test2))
print("AUC TRAINING SMOTED: ", roc_auc_score(y_train,ypred_train2))
print("AUC TESTING SMOTED: ", roc_auc_score(y_test, ypred_test2))
print(" ")
print("CONF MATRIX SMOTED TRAINING NBC")
print(confusion_matrix(y_train,ypred_train2))
print(" ")
print("CONF MATRIX SMOTED TESTING NBC")
print(confusion_matrix(y_test, ypred_test2))
print(" ")
print("Probabilitas Klasifikasi NBC Data Training SMOTE")
print(prob_train2)
print("Probabilitas Klasifikasi NBC Data Testing SMOTE")
print(prob_test2)

HASIL NAIVE BAYES SMOTED
 
AKURASI TRAINING SMOTED:  0.9984101748807631
AKURASI TESTING SMOTED:  1.0
AUC TRAINING SMOTED:  0.9500000000000001
AUC TESTING SMOTED:  1.0
 
CONF MATRIX SMOTED TRAINING NBC
[[  9   1]
 [  0 619]]
 
CONF MATRIX SMOTED TESTING NBC
[[ 2  0]
 [ 0 67]]
 
Probabilitas Klasifikasi NBC Data Training SMOTE
[[8.93555520e-30 1.00000000e+00]
 [2.65460357e-32 1.00000000e+00]
 [4.11095088e-29 1.00000000e+00]
 ...
 [1.13049399e-31 1.00000000e+00]
 [1.01303696e-29 1.00000000e+00]
 [2.69993075e-28 1.00000000e+00]]
Probabilitas Klasifikasi NBC Data Testing SMOTE
[[1.13521008e-51 1.00000000e+00]
 [4.10926885e-54 1.00000000e+00]
 [5.22647991e-53 1.00000000e+00]
 [1.87142649e-45 1.00000000e+00]
 [3.58540309e-67 1.00000000e+00]
 [3.62489125e-45 1.00000000e+00]
 [1.81979269e-52 1.00000000e+00]
 [1.66366463e-58 1.00000000e+00]
 [2.98481483e-56 1.00000000e+00]
 [8.87041764e-58 1.00000000e+00]
 [9.99999956e-01 4.39399708e-08]
 [4.35639412e-54 1.00000000e+00]
 [8.19519978e-48 1.000000